//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collatz_Conjecture {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_tr() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Collatz_Conjecture.lang_tr", typeof(lang_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   adım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string adim {
            get {
                return ResourceManager.GetString("adim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belli Bir Aralığa Bak benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string aralikKutusu {
            get {
                return ResourceManager.GetString("aralikKutusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayarlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ayarlar {
            get {
                return ResourceManager.GetString("ayarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matematik proje ödevim için yaptım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ayarlarAltiAciklama {
            get {
                return ResourceManager.GetString("ayarlarAltiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayarları Sıfırla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ayarlariSifirla {
            get {
                return ResourceManager.GetString("ayarlariSifirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string bilgi {
            get {
                return ResourceManager.GetString("bilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlangıç Sayısı : /Tek Sayı Miktarı : /Çift Sayı Miktarı : /Ulaşılan En Büyük Sayı : /Adım Miktarı :  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string bilgiLabel {
            get {
                return ResourceManager.GetString("bilgiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collatz Sanısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string collatzSanisi {
            get {
                return ResourceManager.GetString("collatzSanisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collatz Sanısı, iki aritmetik işlemin sürekli tekrarlanarak en sonunda tüm pozitif tam sayıların 1&apos;e ulaşacağını anlatan bir sanıdır.
        ///
        ///Eğer sayı çift ise ikiye böl (x/2)
        ///Eğer sayı tek ise üçle çarpıp bir ekle (3x+1) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string collatzSanisiAciklama {
            get {
                return ResourceManager.GetString("collatzSanisiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yerlerini Değiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string degistir {
            get {
                return ResourceManager.GetString("degistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string goster {
            get {
                return ResourceManager.GetString("goster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grafik Rengi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string grafikRengi {
            get {
                return ResourceManager.GetString("grafikRengi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alan
        ///Eğrili Alan
        ///Çizgi
        ///Eğrili Çizgi
        ///Sütun benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string grafikStilEleman {
            get {
                return ResourceManager.GetString("grafikStilEleman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grafik Stili benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string grafikStili {
            get {
                return ResourceManager.GetString("grafikStili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hesapla / Göster tuşuna bastıktan sonra
        ///grafiğiniz burada gözükecektir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hesapBilgilendirme {
            get {
                return ResourceManager.GetString("hesapBilgilendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hesaplanacak Değer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hesapDeger {
            get {
                return ResourceManager.GetString("hesapDeger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hesapla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hesapla {
            get {
                return ResourceManager.GetString("hesapla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaynak Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kaynakKod {
            get {
                return ResourceManager.GetString("kaynakKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Önizleme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string onizleme {
            get {
                return ResourceManager.GetString("onizleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renk Seç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string renkSec {
            get {
                return ResourceManager.GetString("renkSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tamam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tamam {
            get {
                return ResourceManager.GetString("tamam", resourceCulture);
            }
        }
    }
}
