//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collatz_Conjecture {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_en() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Collatz_Conjecture.lang_en", typeof(lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   steps benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string adim {
            get {
                return ResourceManager.GetString("adim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Look at a certain range benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string aralikKutusu {
            get {
                return ResourceManager.GetString("aralikKutusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ayarlar {
            get {
                return ResourceManager.GetString("ayarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I made this for my math project benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ayarlarAltiAciklama {
            get {
                return ResourceManager.GetString("ayarlarAltiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ayarlariSifirla {
            get {
                return ResourceManager.GetString("ayarlariSifirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string bilgi {
            get {
                return ResourceManager.GetString("bilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting Number : /Odd Number Amount : /Even Number Amount : /Greatest Number Reached : /Step Amount :  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string bilgiLabel {
            get {
                return ResourceManager.GetString("bilgiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collatz Conjecture benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string collatzSanisi {
            get {
                return ResourceManager.GetString("collatzSanisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Collatz conjecture asks whether repeating two simple arithmetic operations will eventually transform every positive integer into 1. [Wikipedia]
        ///
        ///If its even, divide it by 2 (x/2)
        ///If its odd, multiply by 3 and add 1 (3x+1) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string collatzSanisiAciklama {
            get {
                return ResourceManager.GetString("collatzSanisiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch Positions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string degistir {
            get {
                return ResourceManager.GetString("degistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string goster {
            get {
                return ResourceManager.GetString("goster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Graph Color benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string grafikRengi {
            get {
                return ResourceManager.GetString("grafikRengi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area
        ///Curved Area
        ///Line
        ///Curved Line
        ///Column benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string grafikStilEleman {
            get {
                return ResourceManager.GetString("grafikStilEleman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Graph Style benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string grafikStili {
            get {
                return ResourceManager.GetString("grafikStili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your graph will be shown here after
        ///clicking Calculate / Show benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hesapBilgilendirme {
            get {
                return ResourceManager.GetString("hesapBilgilendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value to Calculate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hesapDeger {
            get {
                return ResourceManager.GetString("hesapDeger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calculate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hesapla {
            get {
                return ResourceManager.GetString("hesapla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source Code benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kaynakKod {
            get {
                return ResourceManager.GetString("kaynakKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string onizleme {
            get {
                return ResourceManager.GetString("onizleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Color benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string renkSec {
            get {
                return ResourceManager.GetString("renkSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tamam {
            get {
                return ResourceManager.GetString("tamam", resourceCulture);
            }
        }
    }
}
